default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: LucidDreamer_development

test:
  <<: *default
  database: LucidDreamer_test

production:
  <<: *default
  database: LucidDreamer_production
  username: LucidDreamer
  password: <%= ENV['LUCIDDREAMER_DATABASE_PASSWORD'] %>
